sudo: required

services:
  - docker

env:
  global:
    - NAME=postgres

before_deploy:
  - git clone git@github.com:CreditCardsCom/pipeline-scripts.git

deploy:
  provider: script
  script: scripts/publish.sh
  skip_cleanup: true
  on:
    tags: true
