sudo: required

services:
  - docker

env:
  global:
    - NAME=postgres

script:
  - echo "skipping"

deploy:
  provider: script
  script: scripts/publish.sh
  skip_cleanup: true
  on:
    tags: true
